-- 用户表：简化主键约束，修复updated_at默认值写法
CREATE TABLE "users" (
  "uid" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "avatar" varchar(255),
  "bio" varchar(500),
  "created_at" timestamp NOT NULL DEFAULT now(),
  "updated_at" timestamp NOT NULL DEFAULT now(),
  "status" smallint NOT NULL DEFAULT 1
);

-- 关注关系表：简化主键，修复时间字段写法，外键增加ON DELETE CASCADE
CREATE TABLE "follow_relationship" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "follower_uid" bigint NOT NULL,
  "followed_uid" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT now()
);

-- 文章表：修复longtext/tinyint类型，调整publish_at约束，修复时间字段写法
CREATE TABLE "article" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "author_uid" bigint DEFAULT 1,
  "title" varchar(200) NOT NULL,
  "summary" varchar(500),
  "content" text NOT NULL,  -- 替换longtext为text
  "cover_image" varchar(255),
  "status" smallint NOT NULL DEFAULT 0, -- 0:draft, 1:published, 2:deleted
  "view_count" int NOT NULL DEFAULT 0,
  "like_count" int NOT NULL DEFAULT 0,
  "comment_count" int NOT NULL DEFAULT 0,
  "publish_at" timestamp,  -- 草稿无发布时间，改为可NULL，去掉默认值
  "updated_at" timestamp NOT NULL DEFAULT now()
);

-- 分类表：修复tinyint类型和时间字段写法
CREATE TABLE "category" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "sort" smallint NOT NULL DEFAULT 0,  -- 替换tinyint为smallint
  "created_at" timestamp NOT NULL DEFAULT now()
);

-- 文章-分类关联表：简化主键
CREATE TABLE "article_category" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "article_id" bigint NOT NULL,
  "category_id" bigint NOT NULL
);

-- 标签表：修复时间字段写法
CREATE TABLE "tag" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT now()
);

-- 文章-标签关联表：简化主键
CREATE TABLE "article_tag" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "article_id" bigint NOT NULL,
  "tag_id" bigint NOT NULL
);

-- 文章点赞表：简化主键（uid移除外键，单人博客场景）
CREATE TABLE "article_like" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uid" bigint NOT NULL,
  "article_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT now()
);

-- 文章评论表：修复tinyint类型（uid移除外键，单人博客场景）
CREATE TABLE "article_comment" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "article_id" bigint NOT NULL,
  "uid" bigint NOT NULL,
  "content" varchar(1000) NOT NULL,
  "parent_id" bigint,
  "created_at" timestamp NOT NULL DEFAULT now(),
  "status" smallint NOT NULL DEFAULT 1  -- 替换tinyint为smallint
);

-- 显式命名唯一索引，便于维护
CREATE UNIQUE INDEX idx_follow_rel_follower_followed ON "follow_relationship" ("follower_uid", "followed_uid");
CREATE UNIQUE INDEX idx_article_category_article_category ON "article_category" ("article_id", "category_id");
CREATE UNIQUE INDEX idx_article_tag_article_tag ON "article_tag" ("article_id", "tag_id");
CREATE UNIQUE INDEX idx_article_like_uid_article ON "article_like" ("uid", "article_id");

-- 字段注释（保持不变）
COMMENT ON COLUMN "users"."status" IS '1:normal, 0:banned';
COMMENT ON COLUMN "article"."status" IS '0:draft, 1:published, 2:deleted';
COMMENT ON COLUMN "article_comment"."status" IS '1:normal, 0:deleted';

-- 外键约束：只保留指向article和category/tag的约束，删除指向users的约束（单人博客）
ALTER TABLE "article_category" 
  ADD FOREIGN KEY ("article_id") REFERENCES "article" ("id") ON DELETE CASCADE;
ALTER TABLE "article_category" 
  ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id") ON DELETE CASCADE;

ALTER TABLE "article_tag" 
  ADD FOREIGN KEY ("article_id") REFERENCES "article" ("id") ON DELETE CASCADE;
ALTER TABLE "article_tag" 
  ADD FOREIGN KEY ("tag_id") REFERENCES "tag" ("id") ON DELETE CASCADE;

ALTER TABLE "article_like" 
  ADD FOREIGN KEY ("article_id") REFERENCES "article" ("id") ON DELETE CASCADE;

ALTER TABLE "article_comment" 
  ADD FOREIGN KEY ("article_id") REFERENCES "article" ("id") ON DELETE CASCADE;
ALTER TABLE "article_comment" 
  ADD FOREIGN KEY ("parent_id") REFERENCES "article_comment" ("id") ON DELETE SET NULL;

INSERT INTO "users" (username, email, password_hash, status) VALUES ('bro', 'bro@example.com', 'hashed_password', 1);
