-- 用户硬币钱包表
CREATE TABLE coin (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid bigint NOT NULL,
    balance int NOT NULL DEFAULT 0,
    coin_type varchar(50) NOT NULL,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    UNIQUE (uid, coin_type)
    -- 每个用户只能有一个同种coin_type的coin账户
);

ALTER TABLE coin
  ADD FOREIGN KEY (uid) REFERENCES users (uid) ON DELETE CASCADE;


-- 硬币entry记录表
CREATE TABLE coin_entry (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coin_id bigint NOT NULL,
    amount int NOT NULL,
    created_at timestamp DEFAULT now()
);

-- 硬币交易记录表
CREATE TABLE coin_transfer (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_coin_id bigint NOT NULL,
    to_coin_id bigint NOT NULL,
    amount int NOT NULL,
    created_at timestamp DEFAULT now()
);

CREATE INDEX idx_coin_entry_coin_id ON coin_entry(coin_id);
CREATE INDEX idx_coin_transfer_from_coin_id ON coin_transfer(from_coin_id);
CREATE INDEX idx_coin_transfer_to_coin_id ON coin_transfer(to_coin_id);
CREATE INDEX idx_coin_transfer_created_at ON coin_transfer(created_at);

ALTER TABLE coin_entry
  ADD FOREIGN KEY (coin_id) REFERENCES coin (id) ON DELETE CASCADE;
ALTER TABLE coin_transfer
  ADD FOREIGN KEY (from_coin_id) REFERENCES coin (id) ON DELETE CASCADE;
ALTER TABLE coin_transfer
  ADD FOREIGN KEY (to_coin_id) REFERENCES coin (id) ON DELETE CASCADE;


COMMENT ON COLUMN "coin"."coin_type" IS 'penny nickel dime';