-- 用户硬币钱包表
CREATE TABLE coin (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid bigint NOT NULL UNIQUE,
    balance int NOT NULL DEFAULT 0,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE coin
  ADD FOREIGN KEY (uid) REFERENCES users (uid) ON DELETE CASCADE;

-- 每日硬币领取记录表
CREATE TABLE daily_coin_claim (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid bigint NOT NULL,
    claimed_date date NOT NULL,
    claimed_at timestamp DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(uid, claimed_date),
    FOREIGN KEY (uid) REFERENCES users (uid) ON DELETE CASCADE
);

CREATE INDEX idx_daily_coin_claim_uid_date ON daily_coin_claim(uid, claimed_date);

-- 硬币交易记录表
CREATE TABLE coin_transaction (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_uid bigint NOT NULL,
    to_uid bigint NOT NULL,
    amount int NOT NULL,
    transaction_type varchar(50) NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (from_uid) REFERENCES users (uid) ON DELETE CASCADE,
    FOREIGN KEY (to_uid) REFERENCES users (uid) ON DELETE CASCADE
);

CREATE INDEX idx_coin_transaction_from_uid ON coin_transaction(from_uid);
CREATE INDEX idx_coin_transaction_to_uid ON coin_transaction(to_uid);
CREATE INDEX idx_coin_transaction_created_at ON coin_transaction(created_at);

-- 添加follow_relationship外键
ALTER TABLE follow_relationship
  ADD FOREIGN KEY (follower_uid) REFERENCES users (uid) ON DELETE CASCADE;

ALTER TABLE follow_relationship
  ADD FOREIGN KEY (followed_uid) REFERENCES users (uid) ON DELETE CASCADE;