// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: article.sql

package db

import (
	"context"
	"database/sql"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO article(
    author_uid,
    title,
    summary,
    content,
    cover_image,
    status,
    publish_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, author_uid, title, summary, content, cover_image, status, view_count, like_count, comment_count, publish_at, updated_at
`

type CreateArticleParams struct {
	AuthorUid  sql.NullInt64  `json:"author_uid"`
	Title      string         `json:"title"`
	Summary    sql.NullString `json:"summary"`
	Content    string         `json:"content"`
	CoverImage sql.NullString `json:"cover_image"`
	Status     int16          `json:"status"`
	PublishAt  sql.NullTime   `json:"publish_at"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.AuthorUid,
		arg.Title,
		arg.Summary,
		arg.Content,
		arg.CoverImage,
		arg.Status,
		arg.PublishAt,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.AuthorUid,
		&i.Title,
		&i.Summary,
		&i.Content,
		&i.CoverImage,
		&i.Status,
		&i.ViewCount,
		&i.LikeCount,
		&i.CommentCount,
		&i.PublishAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementArticleCommentCount = `-- name: DecrementArticleCommentCount :one
UPDATE article
SET comment_count = GREATEST(comment_count - 1, 0)
WHERE id = $1
RETURNING comment_count
`

func (q *Queries) DecrementArticleCommentCount(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRowContext(ctx, decrementArticleCommentCount, id)
	var comment_count int32
	err := row.Scan(&comment_count)
	return comment_count, err
}

const decrementArticleLikeCount = `-- name: DecrementArticleLikeCount :one
UPDATE article
SET like_count = GREATEST(like_count - 1, 0)
WHERE id = $1
RETURNING like_count
`

func (q *Queries) DecrementArticleLikeCount(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRowContext(ctx, decrementArticleLikeCount, id)
	var like_count int32
	err := row.Scan(&like_count)
	return like_count, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM article
WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteArticle, id)
	return err
}

const getArticle = `-- name: GetArticle :one
SELECT id, author_uid, title, summary, content, cover_image, status, view_count, like_count, comment_count, publish_at, updated_at FROM article
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetArticle(ctx context.Context, id int64) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticle, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.AuthorUid,
		&i.Title,
		&i.Summary,
		&i.Content,
		&i.CoverImage,
		&i.Status,
		&i.ViewCount,
		&i.LikeCount,
		&i.CommentCount,
		&i.PublishAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementArticleCommentCount = `-- name: IncrementArticleCommentCount :one
UPDATE article
SET comment_count = comment_count + 1
WHERE id = $1
RETURNING comment_count
`

func (q *Queries) IncrementArticleCommentCount(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRowContext(ctx, incrementArticleCommentCount, id)
	var comment_count int32
	err := row.Scan(&comment_count)
	return comment_count, err
}

const incrementArticleLikeCount = `-- name: IncrementArticleLikeCount :one
UPDATE article
SET like_count = like_count + 1
WHERE id = $1
RETURNING like_count
`

func (q *Queries) IncrementArticleLikeCount(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRowContext(ctx, incrementArticleLikeCount, id)
	var like_count int32
	err := row.Scan(&like_count)
	return like_count, err
}

const incrementArticleViewCount = `-- name: IncrementArticleViewCount :one
UPDATE article
SET view_count = view_count + 1
WHERE id = $1
RETURNING view_count
`

func (q *Queries) IncrementArticleViewCount(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRowContext(ctx, incrementArticleViewCount, id)
	var view_count int32
	err := row.Scan(&view_count)
	return view_count, err
}

const listArticleByCategory = `-- name: ListArticleByCategory :many
SELECT a.id, a.author_uid, a.title, a.summary, a.content, a.cover_image, a.status, a.view_count, a.like_count, a.comment_count, a.publish_at, a.updated_at
FROM article a
JOIN article_category ac ON a.id = ac.article_id
WHERE ac.category_id = $1
ORDER BY a.publish_at DESC
LIMIT $2
OFFSET $3
`

type ListArticleByCategoryParams struct {
	CategoryID int64 `json:"category_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListArticleByCategory(ctx context.Context, arg ListArticleByCategoryParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listArticleByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.AuthorUid,
			&i.Title,
			&i.Summary,
			&i.Content,
			&i.CoverImage,
			&i.Status,
			&i.ViewCount,
			&i.LikeCount,
			&i.CommentCount,
			&i.PublishAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticleByTag = `-- name: ListArticleByTag :many
SELECT a.id, a.author_uid, a.title, a.summary, a.content, a.cover_image, a.status, a.view_count, a.like_count, a.comment_count, a.publish_at, a.updated_at
FROM article a
JOIN article_tag at ON a.id = at.article_id
WHERE at.tag_id = $1
ORDER BY a.publish_at DESC
LIMIT $2
OFFSET $3
`

type ListArticleByTagParams struct {
	TagID  int64 `json:"tag_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListArticleByTag(ctx context.Context, arg ListArticleByTagParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listArticleByTag, arg.TagID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.AuthorUid,
			&i.Title,
			&i.Summary,
			&i.Content,
			&i.CoverImage,
			&i.Status,
			&i.ViewCount,
			&i.LikeCount,
			&i.CommentCount,
			&i.PublishAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticles = `-- name: ListArticles :many
SELECT id, author_uid, title, summary, content, cover_image, status, view_count, like_count, comment_count, publish_at, updated_at FROM article
ORDER BY publish_at DESC
LIMIT $1 
OFFSET $2
`

type ListArticlesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listArticles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.AuthorUid,
			&i.Title,
			&i.Summary,
			&i.Content,
			&i.CoverImage,
			&i.Status,
			&i.ViewCount,
			&i.LikeCount,
			&i.CommentCount,
			&i.PublishAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByCommentCount = `-- name: ListArticlesByCommentCount :many
SELECT id, author_uid, title, summary, content, cover_image, status, view_count, like_count, comment_count, publish_at, updated_at FROM article
ORDER BY comment_count DESC
LIMIT $1
OFFSET $2
`

type ListArticlesByCommentCountParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListArticlesByCommentCount(ctx context.Context, arg ListArticlesByCommentCountParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesByCommentCount, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.AuthorUid,
			&i.Title,
			&i.Summary,
			&i.Content,
			&i.CoverImage,
			&i.Status,
			&i.ViewCount,
			&i.LikeCount,
			&i.CommentCount,
			&i.PublishAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByLikeCount = `-- name: ListArticlesByLikeCount :many
SELECT id, author_uid, title, summary, content, cover_image, status, view_count, like_count, comment_count, publish_at, updated_at FROM article
ORDER BY like_count DESC
LIMIT $1
OFFSET $2
`

type ListArticlesByLikeCountParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListArticlesByLikeCount(ctx context.Context, arg ListArticlesByLikeCountParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesByLikeCount, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.AuthorUid,
			&i.Title,
			&i.Summary,
			&i.Content,
			&i.CoverImage,
			&i.Status,
			&i.ViewCount,
			&i.LikeCount,
			&i.CommentCount,
			&i.PublishAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByViewCount = `-- name: ListArticlesByViewCount :many
SELECT id, author_uid, title, summary, content, cover_image, status, view_count, like_count, comment_count, publish_at, updated_at FROM article
ORDER BY view_count DESC
LIMIT $1
OFFSET $2
`

type ListArticlesByViewCountParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListArticlesByViewCount(ctx context.Context, arg ListArticlesByViewCountParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesByViewCount, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.AuthorUid,
			&i.Title,
			&i.Summary,
			&i.Content,
			&i.CoverImage,
			&i.Status,
			&i.ViewCount,
			&i.LikeCount,
			&i.CommentCount,
			&i.PublishAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE article
SET
    title = COALESCE($2, title),
    summary = COALESCE($3, summary),
    content = COALESCE($4, content),
    cover_image = COALESCE($5, cover_image),
    status = COALESCE($6, status),
    publish_at = COALESCE($7, publish_at),
    updated_at = now()
WHERE id = $1
RETURNING id, author_uid, title, summary, content, cover_image, status, view_count, like_count, comment_count, publish_at, updated_at
`

type UpdateArticleParams struct {
	ID         int64          `json:"id"`
	Title      string         `json:"title"`
	Summary    sql.NullString `json:"summary"`
	Content    string         `json:"content"`
	CoverImage sql.NullString `json:"cover_image"`
	Status     int16          `json:"status"`
	PublishAt  sql.NullTime   `json:"publish_at"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, updateArticle,
		arg.ID,
		arg.Title,
		arg.Summary,
		arg.Content,
		arg.CoverImage,
		arg.Status,
		arg.PublishAt,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.AuthorUid,
		&i.Title,
		&i.Summary,
		&i.Content,
		&i.CoverImage,
		&i.Status,
		&i.ViewCount,
		&i.LikeCount,
		&i.CommentCount,
		&i.PublishAt,
		&i.UpdatedAt,
	)
	return i, err
}
