// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: article_category.sql

package db

import (
	"context"
)

const createArticleCategory = `-- name: CreateArticleCategory :one
INSERT INTO article_category (article_id, category_id)
VALUES ($1, $2)
RETURNING id, article_id, category_id
`

type CreateArticleCategoryParams struct {
	ArticleID  int64 `json:"article_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) CreateArticleCategory(ctx context.Context, arg CreateArticleCategoryParams) (ArticleCategory, error) {
	row := q.db.QueryRowContext(ctx, createArticleCategory, arg.ArticleID, arg.CategoryID)
	var i ArticleCategory
	err := row.Scan(&i.ID, &i.ArticleID, &i.CategoryID)
	return i, err
}

const deleteArticleCategory = `-- name: DeleteArticleCategory :exec
DELETE FROM article_category
WHERE article_id = $1 AND category_id = $2
`

type DeleteArticleCategoryParams struct {
	ArticleID  int64 `json:"article_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) DeleteArticleCategory(ctx context.Context, arg DeleteArticleCategoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteArticleCategory, arg.ArticleID, arg.CategoryID)
	return err
}

const getArticleCategoryByID = `-- name: GetArticleCategoryByID :one
SELECT id, article_id, category_id
FROM article_category
WHERE id = $1
`

func (q *Queries) GetArticleCategoryByID(ctx context.Context, id int64) (ArticleCategory, error) {
	row := q.db.QueryRowContext(ctx, getArticleCategoryByID, id)
	var i ArticleCategory
	err := row.Scan(&i.ID, &i.ArticleID, &i.CategoryID)
	return i, err
}

const listArticlesByCategoryID = `-- name: ListArticlesByCategoryID :many
SELECT a.id, a.author_uid, a.title, a.summary, a.content, a.cover_image, a.status, a.view_count, a.like_count, a.comment_count, a.publish_at, a.updated_at
FROM article a
JOIN article_category ac ON ac.article_id = a.id
WHERE ac.category_id = $1
ORDER BY a.publish_at DESC
LIMIT $2
OFFSET $3
`

type ListArticlesByCategoryIDParams struct {
	CategoryID int64 `json:"category_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListArticlesByCategoryID(ctx context.Context, arg ListArticlesByCategoryIDParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesByCategoryID, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.AuthorUid,
			&i.Title,
			&i.Summary,
			&i.Content,
			&i.CoverImage,
			&i.Status,
			&i.ViewCount,
			&i.LikeCount,
			&i.CommentCount,
			&i.PublishAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByArticle = `-- name: ListCategoriesByArticle :many
SELECT c.id, c.name, c.sort, c.created_at
FROM category c
JOIN article_category ac ON ac.category_id = c.id
WHERE ac.article_id = $1
ORDER BY c.sort ASC, c.created_at DESC
LIMIT $2
OFFSET $3
`

type ListCategoriesByArticleParams struct {
	ArticleID int64 `json:"article_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListCategoriesByArticle(ctx context.Context, arg ListCategoriesByArticleParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByArticle, arg.ArticleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sort,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
