// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: article_tag.sql

package db

import (
	"context"
)

const createArticleTag = `-- name: CreateArticleTag :one
INSERT INTO article_tag (article_id, tag_id)
VALUES ($1, $2)
RETURNING id, article_id, tag_id
`

type CreateArticleTagParams struct {
	ArticleID int64 `json:"article_id"`
	TagID     int64 `json:"tag_id"`
}

func (q *Queries) CreateArticleTag(ctx context.Context, arg CreateArticleTagParams) (ArticleTag, error) {
	row := q.db.QueryRowContext(ctx, createArticleTag, arg.ArticleID, arg.TagID)
	var i ArticleTag
	err := row.Scan(&i.ID, &i.ArticleID, &i.TagID)
	return i, err
}

const deleteArticleTag = `-- name: DeleteArticleTag :exec
DELETE FROM article_tag
WHERE article_id = $1 AND tag_id = $2
`

type DeleteArticleTagParams struct {
	ArticleID int64 `json:"article_id"`
	TagID     int64 `json:"tag_id"`
}

func (q *Queries) DeleteArticleTag(ctx context.Context, arg DeleteArticleTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteArticleTag, arg.ArticleID, arg.TagID)
	return err
}

const getArticleTagByID = `-- name: GetArticleTagByID :one
SELECT id, article_id, tag_id
FROM article_tag
WHERE id = $1
`

func (q *Queries) GetArticleTagByID(ctx context.Context, id int64) (ArticleTag, error) {
	row := q.db.QueryRowContext(ctx, getArticleTagByID, id)
	var i ArticleTag
	err := row.Scan(&i.ID, &i.ArticleID, &i.TagID)
	return i, err
}

const listArticlesByTagID = `-- name: ListArticlesByTagID :many
SELECT a.id, a.author_uid, a.title, a.summary, a.content, a.cover_image, a.status, a.view_count, a.like_count, a.comment_count, a.publish_at, a.updated_at
FROM article a
JOIN article_tag at ON at.article_id = a.id
WHERE at.tag_id = $1
ORDER BY a.publish_at DESC
LIMIT $2
OFFSET $3
`

type ListArticlesByTagIDParams struct {
	TagID  int64 `json:"tag_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListArticlesByTagID(ctx context.Context, arg ListArticlesByTagIDParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesByTagID, arg.TagID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.AuthorUid,
			&i.Title,
			&i.Summary,
			&i.Content,
			&i.CoverImage,
			&i.Status,
			&i.ViewCount,
			&i.LikeCount,
			&i.CommentCount,
			&i.PublishAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByArticle = `-- name: ListTagsByArticle :many
SELECT t.id, t.name, t.created_at
FROM tag t
JOIN article_tag at ON at.tag_id = t.id
WHERE at.article_id = $1
ORDER BY t.created_at DESC
LIMIT $2
OFFSET $3
`

type ListTagsByArticleParams struct {
	ArticleID int64 `json:"article_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListTagsByArticle(ctx context.Context, arg ListTagsByArticleParams) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByArticle, arg.ArticleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
