// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coin.sql

package db

import (
	"context"
)

const addCoinBalance = `-- name: AddCoinBalance :one
UPDATE coin
SET balance = balance + $1
WHERE id = $2
RETURNING id, uid, balance, coin_type, created_at, updated_at
`

type AddCoinBalanceParams struct {
	Amount int32 `json:"amount"`
	ID     int64 `json:"id"`
}

// 增加硬币余额
func (q *Queries) AddCoinBalance(ctx context.Context, arg AddCoinBalanceParams) (Coin, error) {
	row := q.db.QueryRowContext(ctx, addCoinBalance, arg.Amount, arg.ID)
	var i Coin
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Balance,
		&i.CoinType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCoin = `-- name: CreateCoin :one
INSERT INTO coin (
    uid,
    balance,
    coin_type
)
VALUES (
    $1, $2, $3
) RETURNING id, uid, balance, coin_type, created_at, updated_at
`

type CreateCoinParams struct {
	Uid      int64  `json:"uid"`
	Balance  int32  `json:"balance"`
	CoinType string `json:"coin_type"`
}

// 创建用户硬币钱包
func (q *Queries) CreateCoin(ctx context.Context, arg CreateCoinParams) (Coin, error) {
	row := q.db.QueryRowContext(ctx, createCoin, arg.Uid, arg.Balance, arg.CoinType)
	var i Coin
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Balance,
		&i.CoinType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCoin = `-- name: DeleteCoin :exec
DELETE FROM coin
WHERE id = $1
`

// 删除硬币账户
func (q *Queries) DeleteCoin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCoin, id)
	return err
}

const getCoin = `-- name: GetCoin :one
SELECT id, uid, balance, coin_type, created_at, updated_at 
FROM coin 
WHERE id = $1
`

// 获取coin余额
func (q *Queries) GetCoin(ctx context.Context, id int64) (Coin, error) {
	row := q.db.QueryRowContext(ctx, getCoin, id)
	var i Coin
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Balance,
		&i.CoinType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCoins = `-- name: ListCoins :many
SELECT id, uid, balance, coin_type, created_at, updated_at FROM coin
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListCoinsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// 列出coin的账号
func (q *Queries) ListCoins(ctx context.Context, arg ListCoinsParams) ([]Coin, error) {
	rows, err := q.db.QueryContext(ctx, listCoins, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Coin{}
	for rows.Next() {
		var i Coin
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.Balance,
			&i.CoinType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoinsForUser = `-- name: ListCoinsForUser :many
SELECT id, uid, balance, coin_type, created_at, updated_at FROM coin
WHERE uid = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListCoinsForUserParams struct {
	Uid    int64 `json:"uid"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// 列出用户的账号
func (q *Queries) ListCoinsForUser(ctx context.Context, arg ListCoinsForUserParams) ([]Coin, error) {
	rows, err := q.db.QueryContext(ctx, listCoinsForUser, arg.Uid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Coin{}
	for rows.Next() {
		var i Coin
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.Balance,
			&i.CoinType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoin = `-- name: UpdateCoin :one
UPDATE coin
SET balance = $2
WHERE id = $1
RETURNING id, uid, balance, coin_type, created_at, updated_at
`

type UpdateCoinParams struct {
	ID      int64 `json:"id"`
	Balance int32 `json:"balance"`
}

// 更新用户硬币余额
func (q *Queries) UpdateCoin(ctx context.Context, arg UpdateCoinParams) (Coin, error) {
	row := q.db.QueryRowContext(ctx, updateCoin, arg.ID, arg.Balance)
	var i Coin
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Balance,
		&i.CoinType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
