// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coin_transfer.sql

package db

import (
	"context"
)

const createCoinTransfer = `-- name: CreateCoinTransfer :one
INSERT INTO coin_transfer(
    from_uid,
    to_uid,
    amount
)VALUES(
    $1, $2, $3
)RETURNING id, from_uid, to_uid, amount, created_at
`

type CreateCoinTransferParams struct {
	FromUid int64 `json:"from_uid"`
	ToUid   int64 `json:"to_uid"`
	Amount  int32 `json:"amount"`
}

// 用户之间转账硬币
func (q *Queries) CreateCoinTransfer(ctx context.Context, arg CreateCoinTransferParams) (CoinTransfer, error) {
	row := q.db.QueryRowContext(ctx, createCoinTransfer, arg.FromUid, arg.ToUid, arg.Amount)
	var i CoinTransfer
	err := row.Scan(
		&i.ID,
		&i.FromUid,
		&i.ToUid,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getCoinTransfer = `-- name: GetCoinTransfer :one
SELECT id, from_uid, to_uid, amount, created_at FROM coin_transfer
WHERE id = $1 LIMIT 1
`

// 获取一个硬币交易
func (q *Queries) GetCoinTransfer(ctx context.Context, id int64) (CoinTransfer, error) {
	row := q.db.QueryRowContext(ctx, getCoinTransfer, id)
	var i CoinTransfer
	err := row.Scan(
		&i.ID,
		&i.FromUid,
		&i.ToUid,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getCoinTransferCount = `-- name: GetCoinTransferCount :one
SELECT COUNT(*) FROM coin_transfer WHERE from_uid = $1 OR to_uid = $1
`

// 获取用户的转账总数
func (q *Queries) GetCoinTransferCount(ctx context.Context, fromUid int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCoinTransferCount, fromUid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCoinTransferReceived = `-- name: GetCoinTransferReceived :many
SELECT id, from_uid, to_uid, amount, created_at FROM coin_transfer
WHERE to_uid = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetCoinTransferReceivedParams struct {
	ToUid  int64 `json:"to_uid"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// 获取用户作为接收方的交易记录
func (q *Queries) GetCoinTransferReceived(ctx context.Context, arg GetCoinTransferReceivedParams) ([]CoinTransfer, error) {
	rows, err := q.db.QueryContext(ctx, getCoinTransferReceived, arg.ToUid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoinTransfer{}
	for rows.Next() {
		var i CoinTransfer
		if err := rows.Scan(
			&i.ID,
			&i.FromUid,
			&i.ToUid,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoinTransfer = `-- name: ListCoinTransfer :many
SELECT id, from_uid, to_uid, amount, created_at FROM coin_transfer
WHERE 
    from_uid = $1 OR
    to_uid = $2
ORDER BY id
LIMIT $3
OFFSET $4
`

type ListCoinTransferParams struct {
	FromUid int64 `json:"from_uid"`
	ToUid   int64 `json:"to_uid"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

// 列出一页硬币的交易
func (q *Queries) ListCoinTransfer(ctx context.Context, arg ListCoinTransferParams) ([]CoinTransfer, error) {
	rows, err := q.db.QueryContext(ctx, listCoinTransfer,
		arg.FromUid,
		arg.ToUid,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoinTransfer{}
	for rows.Next() {
		var i CoinTransfer
		if err := rows.Scan(
			&i.ID,
			&i.FromUid,
			&i.ToUid,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfer = `-- name: ListTransfer :many
SELECT id, from_uid, to_uid, amount, created_at FROM coin_transfer
WHERE from_uid = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransferParams struct {
	FromUid int64 `json:"from_uid"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

// 获取用户作为发送方的交易记录
func (q *Queries) ListTransfer(ctx context.Context, arg ListTransferParams) ([]CoinTransfer, error) {
	rows, err := q.db.QueryContext(ctx, listTransfer, arg.FromUid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoinTransfer{}
	for rows.Next() {
		var i CoinTransfer
		if err := rows.Scan(
			&i.ID,
			&i.FromUid,
			&i.ToUid,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
