// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coin_entry.sql

package db

import (
	"context"
)

const createCoinEntry = `-- name: CreateCoinEntry :one
INSERT INTO coin_entry (coin_id, amount) VALUES ($1, $2) RETURNING id, coin_id, amount, created_at
`

type CreateCoinEntryParams struct {
	CoinID int64 `json:"coin_id"`
	Amount int32 `json:"amount"`
}

// 创建硬币entry记录
func (q *Queries) CreateCoinEntry(ctx context.Context, arg CreateCoinEntryParams) (CoinEntry, error) {
	row := q.db.QueryRowContext(ctx, createCoinEntry, arg.CoinID, arg.Amount)
	var i CoinEntry
	err := row.Scan(
		&i.ID,
		&i.CoinID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getCoinEntry = `-- name: GetCoinEntry :one
SELECT id, coin_id, amount, created_at FROM coin_entry
WHERE id = $1 LIMIT 1
`

// 获取一个entry记录
func (q *Queries) GetCoinEntry(ctx context.Context, id int64) (CoinEntry, error) {
	row := q.db.QueryRowContext(ctx, getCoinEntry, id)
	var i CoinEntry
	err := row.Scan(
		&i.ID,
		&i.CoinID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getCoinEntryCount = `-- name: GetCoinEntryCount :one
SELECT COUNT(*) FROM coin_entry WHERE coin_id = $1
`

// 获取用户的硬币entry总数
func (q *Queries) GetCoinEntryCount(ctx context.Context, coinID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCoinEntryCount, coinID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listEntries = `-- name: ListEntries :many
SELECT id, coin_id, amount, created_at FROM coin_entry
WHERE coin_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListEntriesParams struct {
	CoinID int64 `json:"coin_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]CoinEntry, error) {
	rows, err := q.db.QueryContext(ctx, listEntries, arg.CoinID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoinEntry{}
	for rows.Next() {
		var i CoinEntry
		if err := rows.Scan(
			&i.ID,
			&i.CoinID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
