// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comment.sql

package db

import (
	"context"
	"database/sql"
)

const createComment = `-- name: CreateComment :one
INSERT INTO article_comment (
    article_id,
    uid,
    content,
    parent_id,
    status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, article_id, uid, content, parent_id, created_at, status
`

type CreateCommentParams struct {
	ArticleID int64         `json:"article_id"`
	Uid       int64         `json:"uid"`
	Content   string        `json:"content"`
	ParentID  sql.NullInt64 `json:"parent_id"`
	Status    int16         `json:"status"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (ArticleComment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.ArticleID,
		arg.Uid,
		arg.Content,
		arg.ParentID,
		arg.Status,
	)
	var i ArticleComment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.Uid,
		&i.Content,
		&i.ParentID,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM article_comment
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, article_id, uid, content, parent_id, created_at, status FROM article_comment
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetComment(ctx context.Context, id int64) (ArticleComment, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i ArticleComment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.Uid,
		&i.Content,
		&i.ParentID,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const listComments = `-- name: ListComments :many
SELECT id, article_id, uid, content, parent_id, created_at, status FROM article_comment
WHERE article_id = $1
ORDER BY created_at ASC
LIMIT $2 
OFFSET $3
`

type ListCommentsParams struct {
	ArticleID int64 `json:"article_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]ArticleComment, error) {
	rows, err := q.db.QueryContext(ctx, listComments, arg.ArticleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArticleComment{}
	for rows.Next() {
		var i ArticleComment
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.Uid,
			&i.Content,
			&i.ParentID,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
