// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: follow_relationship.sql

package db

import (
	"context"
)

const createFollowRelationship = `-- name: CreateFollowRelationship :one
INSERT INTO follow_relationship (follower_uid, followed_uid, created_at)
VALUES ($1, $2, now())
RETURNING id, follower_uid, followed_uid, created_at
`

type CreateFollowRelationshipParams struct {
	FollowerUid int64 `json:"follower_uid"`
	FollowedUid int64 `json:"followed_uid"`
}

func (q *Queries) CreateFollowRelationship(ctx context.Context, arg CreateFollowRelationshipParams) (FollowRelationship, error) {
	row := q.db.QueryRowContext(ctx, createFollowRelationship, arg.FollowerUid, arg.FollowedUid)
	var i FollowRelationship
	err := row.Scan(
		&i.ID,
		&i.FollowerUid,
		&i.FollowedUid,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFollowRelationship = `-- name: DeleteFollowRelationship :exec
DELETE FROM follow_relationship
WHERE follower_uid = $1 AND followed_uid = $2
`

type DeleteFollowRelationshipParams struct {
	FollowerUid int64 `json:"follower_uid"`
	FollowedUid int64 `json:"followed_uid"`
}

func (q *Queries) DeleteFollowRelationship(ctx context.Context, arg DeleteFollowRelationshipParams) error {
	_, err := q.db.ExecContext(ctx, deleteFollowRelationship, arg.FollowerUid, arg.FollowedUid)
	return err
}

const getFollowRelationship = `-- name: GetFollowRelationship :one
SELECT id, follower_uid, followed_uid, created_at
FROM follow_relationship
WHERE follower_uid = $1 AND followed_uid = $2
`

type GetFollowRelationshipParams struct {
	FollowerUid int64 `json:"follower_uid"`
	FollowedUid int64 `json:"followed_uid"`
}

func (q *Queries) GetFollowRelationship(ctx context.Context, arg GetFollowRelationshipParams) (FollowRelationship, error) {
	row := q.db.QueryRowContext(ctx, getFollowRelationship, arg.FollowerUid, arg.FollowedUid)
	var i FollowRelationship
	err := row.Scan(
		&i.ID,
		&i.FollowerUid,
		&i.FollowedUid,
		&i.CreatedAt,
	)
	return i, err
}

const getFollowRelationshipByID = `-- name: GetFollowRelationshipByID :one
SELECT id, follower_uid, followed_uid, created_at
FROM follow_relationship
WHERE id = $1
`

func (q *Queries) GetFollowRelationshipByID(ctx context.Context, id int64) (FollowRelationship, error) {
	row := q.db.QueryRowContext(ctx, getFollowRelationshipByID, id)
	var i FollowRelationship
	err := row.Scan(
		&i.ID,
		&i.FollowerUid,
		&i.FollowedUid,
		&i.CreatedAt,
	)
	return i, err
}

const listFollowers = `-- name: ListFollowers :many
SELECT id, follower_uid, followed_uid, created_at
FROM follow_relationship
WHERE followed_uid = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListFollowersParams struct {
	FollowedUid int64 `json:"followed_uid"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]FollowRelationship, error) {
	rows, err := q.db.QueryContext(ctx, listFollowers, arg.FollowedUid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FollowRelationship{}
	for rows.Next() {
		var i FollowRelationship
		if err := rows.Scan(
			&i.ID,
			&i.FollowerUid,
			&i.FollowedUid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT id, follower_uid, followed_uid, created_at
FROM follow_relationship
WHERE follower_uid = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListFollowingParams struct {
	FollowerUid int64 `json:"follower_uid"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

func (q *Queries) ListFollowing(ctx context.Context, arg ListFollowingParams) ([]FollowRelationship, error) {
	rows, err := q.db.QueryContext(ctx, listFollowing, arg.FollowerUid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FollowRelationship{}
	for rows.Next() {
		var i FollowRelationship
		if err := rows.Scan(
			&i.ID,
			&i.FollowerUid,
			&i.FollowedUid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
