// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: like.sql

package db

import (
	"context"
)

const createArticleLike = `-- name: CreateArticleLike :one
INSERT INTO article_like (uid, article_id, created_at)
VALUES ($1, $2, now())
RETURNING id, uid, article_id, created_at
`

type CreateArticleLikeParams struct {
	Uid       int64 `json:"uid"`
	ArticleID int64 `json:"article_id"`
}

func (q *Queries) CreateArticleLike(ctx context.Context, arg CreateArticleLikeParams) (ArticleLike, error) {
	row := q.db.QueryRowContext(ctx, createArticleLike, arg.Uid, arg.ArticleID)
	var i ArticleLike
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.ArticleID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArticleLike = `-- name: DeleteArticleLike :exec
DELETE FROM article_like
WHERE uid = $1 AND article_id = $2
`

type DeleteArticleLikeParams struct {
	Uid       int64 `json:"uid"`
	ArticleID int64 `json:"article_id"`
}

func (q *Queries) DeleteArticleLike(ctx context.Context, arg DeleteArticleLikeParams) error {
	_, err := q.db.ExecContext(ctx, deleteArticleLike, arg.Uid, arg.ArticleID)
	return err
}

const getArticleLike = `-- name: GetArticleLike :one
SELECT id, uid, article_id, created_at
FROM article_like
WHERE uid = $1 AND article_id = $2
`

type GetArticleLikeParams struct {
	Uid       int64 `json:"uid"`
	ArticleID int64 `json:"article_id"`
}

func (q *Queries) GetArticleLike(ctx context.Context, arg GetArticleLikeParams) (ArticleLike, error) {
	row := q.db.QueryRowContext(ctx, getArticleLike, arg.Uid, arg.ArticleID)
	var i ArticleLike
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.ArticleID,
		&i.CreatedAt,
	)
	return i, err
}

const getArticleLikeByID = `-- name: GetArticleLikeByID :one
SELECT id, uid, article_id, created_at
FROM article_like
WHERE id = $1
`

func (q *Queries) GetArticleLikeByID(ctx context.Context, id int64) (ArticleLike, error) {
	row := q.db.QueryRowContext(ctx, getArticleLikeByID, id)
	var i ArticleLike
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.ArticleID,
		&i.CreatedAt,
	)
	return i, err
}

const listArticleLikesByArticle = `-- name: ListArticleLikesByArticle :many
SELECT id, uid, article_id, created_at
FROM article_like
WHERE article_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListArticleLikesByArticleParams struct {
	ArticleID int64 `json:"article_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListArticleLikesByArticle(ctx context.Context, arg ListArticleLikesByArticleParams) ([]ArticleLike, error) {
	rows, err := q.db.QueryContext(ctx, listArticleLikesByArticle, arg.ArticleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArticleLike{}
	for rows.Next() {
		var i ArticleLike
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.ArticleID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
