// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Article struct {
	ID         int64          `json:"id"`
	AuthorUid  sql.NullInt64  `json:"author_uid"`
	Title      string         `json:"title"`
	Summary    sql.NullString `json:"summary"`
	Content    string         `json:"content"`
	CoverImage sql.NullString `json:"cover_image"`
	// 0:draft, 1:published, 2:deleted
	Status       int16        `json:"status"`
	ViewCount    int32        `json:"view_count"`
	LikeCount    int32        `json:"like_count"`
	CommentCount int32        `json:"comment_count"`
	PublishAt    sql.NullTime `json:"publish_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

type ArticleCategory struct {
	ID         int64 `json:"id"`
	ArticleID  int64 `json:"article_id"`
	CategoryID int64 `json:"category_id"`
}

type ArticleComment struct {
	ID        int64         `json:"id"`
	ArticleID int64         `json:"article_id"`
	Uid       int64         `json:"uid"`
	Content   string        `json:"content"`
	ParentID  sql.NullInt64 `json:"parent_id"`
	CreatedAt time.Time     `json:"created_at"`
	// 1:normal, 0:deleted
	Status int16 `json:"status"`
}

type ArticleLike struct {
	ID        int64     `json:"id"`
	Uid       int64     `json:"uid"`
	ArticleID int64     `json:"article_id"`
	CreatedAt time.Time `json:"created_at"`
}

type ArticleTag struct {
	ID        int64 `json:"id"`
	ArticleID int64 `json:"article_id"`
	TagID     int64 `json:"tag_id"`
}

type Category struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Sort      int16     `json:"sort"`
	CreatedAt time.Time `json:"created_at"`
}

type FollowRelationship struct {
	ID          int64     `json:"id"`
	FollowerUid int64     `json:"follower_uid"`
	FollowedUid int64     `json:"followed_uid"`
	CreatedAt   time.Time `json:"created_at"`
}

type Tag struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Users struct {
	Uid          int64          `json:"uid"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Avatar       sql.NullString `json:"avatar"`
	Bio          sql.NullString `json:"bio"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	// 1:normal, 0:banned
	Status int16 `json:"status"`
}
