// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// 增加硬币余额
	AddCoinBalance(ctx context.Context, arg AddCoinBalanceParams) (Coin, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error)
	CreateArticleCategory(ctx context.Context, arg CreateArticleCategoryParams) (ArticleCategory, error)
	CreateArticleLike(ctx context.Context, arg CreateArticleLikeParams) (ArticleLike, error)
	CreateArticleTag(ctx context.Context, arg CreateArticleTagParams) (ArticleTag, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	// 创建用户硬币钱包
	CreateCoin(ctx context.Context, arg CreateCoinParams) (Coin, error)
	// 创建硬币entry记录
	CreateCoinEntry(ctx context.Context, arg CreateCoinEntryParams) (CoinEntry, error)
	// 用户之间转账硬币
	CreateCoinTransfer(ctx context.Context, arg CreateCoinTransferParams) (CoinTransfer, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (ArticleComment, error)
	CreateFollowRelationship(ctx context.Context, arg CreateFollowRelationshipParams) (FollowRelationship, error)
	CreateTag(ctx context.Context, name string) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	DecrementArticleCommentCount(ctx context.Context, id int64) (int32, error)
	DecrementArticleLikeCount(ctx context.Context, id int64) (int32, error)
	DeleteArticle(ctx context.Context, id int64) error
	DeleteArticleCategory(ctx context.Context, arg DeleteArticleCategoryParams) error
	DeleteArticleLike(ctx context.Context, arg DeleteArticleLikeParams) error
	DeleteArticleTag(ctx context.Context, arg DeleteArticleTagParams) error
	DeleteCategory(ctx context.Context, id int64) error
	// 删除硬币账户
	DeleteCoin(ctx context.Context, id int64) error
	DeleteComment(ctx context.Context, id int64) error
	DeleteFollowRelationship(ctx context.Context, arg DeleteFollowRelationshipParams) error
	DeleteTag(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, uid int64) error
	GetArticle(ctx context.Context, id int64) (Article, error)
	GetArticleCategoryByID(ctx context.Context, id int64) (ArticleCategory, error)
	GetArticleLike(ctx context.Context, arg GetArticleLikeParams) (ArticleLike, error)
	GetArticleLikeByID(ctx context.Context, id int64) (ArticleLike, error)
	GetArticleTagByID(ctx context.Context, id int64) (ArticleTag, error)
	GetCategoryByID(ctx context.Context, id int64) (Category, error)
	// 获取coin余额
	GetCoin(ctx context.Context, id int64) (Coin, error)
	// 获取一个entry记录
	GetCoinEntry(ctx context.Context, id int64) (CoinEntry, error)
	// 获取用户的硬币entry总数
	GetCoinEntryCount(ctx context.Context, coinID int64) (int64, error)
	// 获取一个硬币交易
	GetCoinTransfer(ctx context.Context, id int64) (CoinTransfer, error)
	// 获取用户的转账总数
	GetCoinTransferCount(ctx context.Context, fromCoinID int64) (int64, error)
	// 获取用户作为接收方的交易记录
	GetCoinTransferReceived(ctx context.Context, arg GetCoinTransferReceivedParams) ([]CoinTransfer, error)
	GetComment(ctx context.Context, id int64) (ArticleComment, error)
	GetFollowRelationship(ctx context.Context, arg GetFollowRelationshipParams) (FollowRelationship, error)
	GetFollowRelationshipByID(ctx context.Context, id int64) (FollowRelationship, error)
	GetTagByID(ctx context.Context, id int64) (Tag, error)
	GetTagByName(ctx context.Context, name string) (Tag, error)
	GetUser(ctx context.Context, uid int64) (Users, error)
	IncrementArticleCommentCount(ctx context.Context, id int64) (int32, error)
	IncrementArticleLikeCount(ctx context.Context, id int64) (int32, error)
	IncrementArticleViewCount(ctx context.Context, id int64) (int32, error)
	ListArticleByCategory(ctx context.Context, arg ListArticleByCategoryParams) ([]Article, error)
	ListArticleByTag(ctx context.Context, arg ListArticleByTagParams) ([]Article, error)
	ListArticleLikesByArticle(ctx context.Context, arg ListArticleLikesByArticleParams) ([]ArticleLike, error)
	ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error)
	ListArticlesByCategoryID(ctx context.Context, arg ListArticlesByCategoryIDParams) ([]Article, error)
	ListArticlesByCommentCount(ctx context.Context, arg ListArticlesByCommentCountParams) ([]Article, error)
	ListArticlesByLikeCount(ctx context.Context, arg ListArticlesByLikeCountParams) ([]Article, error)
	ListArticlesByTagID(ctx context.Context, arg ListArticlesByTagIDParams) ([]Article, error)
	ListArticlesByViewCount(ctx context.Context, arg ListArticlesByViewCountParams) ([]Article, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListCategoriesByArticle(ctx context.Context, arg ListCategoriesByArticleParams) ([]Category, error)
	// 列出一页硬币的交易
	ListCoinTransfer(ctx context.Context, arg ListCoinTransferParams) ([]CoinTransfer, error)
	// 列出coin的账号
	ListCoins(ctx context.Context, arg ListCoinsParams) ([]Coin, error)
	// 列出用户的账号
	ListCoinsForUser(ctx context.Context, arg ListCoinsForUserParams) ([]Coin, error)
	ListComments(ctx context.Context, arg ListCommentsParams) ([]ArticleComment, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]CoinEntry, error)
	ListFollowers(ctx context.Context, arg ListFollowersParams) ([]FollowRelationship, error)
	ListFollowing(ctx context.Context, arg ListFollowingParams) ([]FollowRelationship, error)
	ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error)
	ListTagsByArticle(ctx context.Context, arg ListTagsByArticleParams) ([]Tag, error)
	// 获取用户作为发送方的交易记录
	ListTransfer(ctx context.Context, arg ListTransferParams) ([]CoinTransfer, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]Users, error)
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	// 更新用户硬币余额
	UpdateCoin(ctx context.Context, arg UpdateCoinParams) (Coin, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error)
}

var _ Querier = (*Queries)(nil)
