// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username,
  email,
  password_hash
) VALUES (
  $1, $2, $3
)
RETURNING uid, username, email, password_hash, avatar, bio, created_at, updated_at, status
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i Users
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Avatar,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE uid = $1
`

func (q *Queries) DeleteUser(ctx context.Context, uid int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, uid)
	return err
}

const getUser = `-- name: GetUser :one
SELECT uid, username, email, password_hash, avatar, bio, created_at, updated_at, status FROM users
WHERE uid = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, uid int64) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUser, uid)
	var i Users
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Avatar,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT uid, username, email, password_hash, avatar, bio, created_at, updated_at, status FROM users
ORDER BY uid
LIMIT $1 
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]Users, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Users{}
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.Uid,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Avatar,
			&i.Bio,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  username = COALESCE(NULLIF($1, ''), username),
  email = COALESCE(NULLIF($2, ''), email),
  password_hash = COALESCE(NULLIF($3, ''), password_hash),
  avatar = COALESCE($4, avatar),
  bio = COALESCE($5, bio),
  updated_at = now(),
  status = COALESCE(NULLIF($6, 0), status)
WHERE uid = $7
RETURNING uid, username, email, password_hash, avatar, bio, created_at, updated_at, status
`

type UpdateUserParams struct {
	Username     interface{}    `json:"username"`
	Email        interface{}    `json:"email"`
	PasswordHash interface{}    `json:"password_hash"`
	Avatar       sql.NullString `json:"avatar"`
	Bio          sql.NullString `json:"bio"`
	Status       interface{}    `json:"status"`
	Uid          int64          `json:"uid"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Avatar,
		arg.Bio,
		arg.Status,
		arg.Uid,
	)
	var i Users
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Avatar,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}
