name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: website
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -h localhost -U root -d website" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5  
        with:
          go-version: ^1.25

      - name: Check out code  
        uses: actions/checkout@v4

      - name: install migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.19.1/migrate.darwin-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/migrate
          which migrate

      - name: run migrations
        run: make migrateup
      
      - name: Test
        run: make test

