// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/BroMikey/blog_backend/db/sqlc (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination db/mock/store.go -package mockdb github.com/BroMikey/blog_backend/db/sqlc Store
//

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	db "github.com/BroMikey/blog_backend/db/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddCoinBalance mocks base method.
func (m *MockStore) AddCoinBalance(ctx context.Context, arg db.AddCoinBalanceParams) (db.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCoinBalance", ctx, arg)
	ret0, _ := ret[0].(db.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCoinBalance indicates an expected call of AddCoinBalance.
func (mr *MockStoreMockRecorder) AddCoinBalance(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCoinBalance", reflect.TypeOf((*MockStore)(nil).AddCoinBalance), ctx, arg)
}

// CoinTransferTx mocks base method.
func (m *MockStore) CoinTransferTx(ctx context.Context, arg db.CoinTransferTxParams) (db.CoinTransferTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CoinTransferTx", ctx, arg)
	ret0, _ := ret[0].(db.CoinTransferTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CoinTransferTx indicates an expected call of CoinTransferTx.
func (mr *MockStoreMockRecorder) CoinTransferTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CoinTransferTx", reflect.TypeOf((*MockStore)(nil).CoinTransferTx), ctx, arg)
}

// CreateArticle mocks base method.
func (m *MockStore) CreateArticle(ctx context.Context, arg db.CreateArticleParams) (db.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArticle", ctx, arg)
	ret0, _ := ret[0].(db.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticle indicates an expected call of CreateArticle.
func (mr *MockStoreMockRecorder) CreateArticle(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticle", reflect.TypeOf((*MockStore)(nil).CreateArticle), ctx, arg)
}

// CreateArticleCategory mocks base method.
func (m *MockStore) CreateArticleCategory(ctx context.Context, arg db.CreateArticleCategoryParams) (db.ArticleCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArticleCategory", ctx, arg)
	ret0, _ := ret[0].(db.ArticleCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticleCategory indicates an expected call of CreateArticleCategory.
func (mr *MockStoreMockRecorder) CreateArticleCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticleCategory", reflect.TypeOf((*MockStore)(nil).CreateArticleCategory), ctx, arg)
}

// CreateArticleLike mocks base method.
func (m *MockStore) CreateArticleLike(ctx context.Context, arg db.CreateArticleLikeParams) (db.ArticleLike, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArticleLike", ctx, arg)
	ret0, _ := ret[0].(db.ArticleLike)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticleLike indicates an expected call of CreateArticleLike.
func (mr *MockStoreMockRecorder) CreateArticleLike(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticleLike", reflect.TypeOf((*MockStore)(nil).CreateArticleLike), ctx, arg)
}

// CreateArticleTag mocks base method.
func (m *MockStore) CreateArticleTag(ctx context.Context, arg db.CreateArticleTagParams) (db.ArticleTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArticleTag", ctx, arg)
	ret0, _ := ret[0].(db.ArticleTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticleTag indicates an expected call of CreateArticleTag.
func (mr *MockStoreMockRecorder) CreateArticleTag(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticleTag", reflect.TypeOf((*MockStore)(nil).CreateArticleTag), ctx, arg)
}

// CreateCategory mocks base method.
func (m *MockStore) CreateCategory(ctx context.Context, arg db.CreateCategoryParams) (db.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, arg)
	ret0, _ := ret[0].(db.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockStoreMockRecorder) CreateCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockStore)(nil).CreateCategory), ctx, arg)
}

// CreateCoin mocks base method.
func (m *MockStore) CreateCoin(ctx context.Context, arg db.CreateCoinParams) (db.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCoin", ctx, arg)
	ret0, _ := ret[0].(db.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCoin indicates an expected call of CreateCoin.
func (mr *MockStoreMockRecorder) CreateCoin(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCoin", reflect.TypeOf((*MockStore)(nil).CreateCoin), ctx, arg)
}

// CreateCoinEntry mocks base method.
func (m *MockStore) CreateCoinEntry(ctx context.Context, arg db.CreateCoinEntryParams) (db.CoinEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCoinEntry", ctx, arg)
	ret0, _ := ret[0].(db.CoinEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCoinEntry indicates an expected call of CreateCoinEntry.
func (mr *MockStoreMockRecorder) CreateCoinEntry(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCoinEntry", reflect.TypeOf((*MockStore)(nil).CreateCoinEntry), ctx, arg)
}

// CreateCoinTransfer mocks base method.
func (m *MockStore) CreateCoinTransfer(ctx context.Context, arg db.CreateCoinTransferParams) (db.CoinTransfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCoinTransfer", ctx, arg)
	ret0, _ := ret[0].(db.CoinTransfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCoinTransfer indicates an expected call of CreateCoinTransfer.
func (mr *MockStoreMockRecorder) CreateCoinTransfer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCoinTransfer", reflect.TypeOf((*MockStore)(nil).CreateCoinTransfer), ctx, arg)
}

// CreateComment mocks base method.
func (m *MockStore) CreateComment(ctx context.Context, arg db.CreateCommentParams) (db.ArticleComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", ctx, arg)
	ret0, _ := ret[0].(db.ArticleComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockStoreMockRecorder) CreateComment(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockStore)(nil).CreateComment), ctx, arg)
}

// CreateFollowRelationship mocks base method.
func (m *MockStore) CreateFollowRelationship(ctx context.Context, arg db.CreateFollowRelationshipParams) (db.FollowRelationship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFollowRelationship", ctx, arg)
	ret0, _ := ret[0].(db.FollowRelationship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFollowRelationship indicates an expected call of CreateFollowRelationship.
func (mr *MockStoreMockRecorder) CreateFollowRelationship(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFollowRelationship", reflect.TypeOf((*MockStore)(nil).CreateFollowRelationship), ctx, arg)
}

// CreateTag mocks base method.
func (m *MockStore) CreateTag(ctx context.Context, name string) (db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTag", ctx, name)
	ret0, _ := ret[0].(db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTag indicates an expected call of CreateTag.
func (mr *MockStoreMockRecorder) CreateTag(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTag", reflect.TypeOf((*MockStore)(nil).CreateTag), ctx, name)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(db.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), ctx, arg)
}

// DecrementArticleCommentCount mocks base method.
func (m *MockStore) DecrementArticleCommentCount(ctx context.Context, id int64) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementArticleCommentCount", ctx, id)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementArticleCommentCount indicates an expected call of DecrementArticleCommentCount.
func (mr *MockStoreMockRecorder) DecrementArticleCommentCount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementArticleCommentCount", reflect.TypeOf((*MockStore)(nil).DecrementArticleCommentCount), ctx, id)
}

// DecrementArticleLikeCount mocks base method.
func (m *MockStore) DecrementArticleLikeCount(ctx context.Context, id int64) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementArticleLikeCount", ctx, id)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementArticleLikeCount indicates an expected call of DecrementArticleLikeCount.
func (mr *MockStoreMockRecorder) DecrementArticleLikeCount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementArticleLikeCount", reflect.TypeOf((*MockStore)(nil).DecrementArticleLikeCount), ctx, id)
}

// DeleteArticle mocks base method.
func (m *MockStore) DeleteArticle(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticle", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArticle indicates an expected call of DeleteArticle.
func (mr *MockStoreMockRecorder) DeleteArticle(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticle", reflect.TypeOf((*MockStore)(nil).DeleteArticle), ctx, id)
}

// DeleteArticleCategory mocks base method.
func (m *MockStore) DeleteArticleCategory(ctx context.Context, arg db.DeleteArticleCategoryParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticleCategory", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArticleCategory indicates an expected call of DeleteArticleCategory.
func (mr *MockStoreMockRecorder) DeleteArticleCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticleCategory", reflect.TypeOf((*MockStore)(nil).DeleteArticleCategory), ctx, arg)
}

// DeleteArticleLike mocks base method.
func (m *MockStore) DeleteArticleLike(ctx context.Context, arg db.DeleteArticleLikeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticleLike", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArticleLike indicates an expected call of DeleteArticleLike.
func (mr *MockStoreMockRecorder) DeleteArticleLike(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticleLike", reflect.TypeOf((*MockStore)(nil).DeleteArticleLike), ctx, arg)
}

// DeleteArticleTag mocks base method.
func (m *MockStore) DeleteArticleTag(ctx context.Context, arg db.DeleteArticleTagParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticleTag", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArticleTag indicates an expected call of DeleteArticleTag.
func (mr *MockStoreMockRecorder) DeleteArticleTag(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticleTag", reflect.TypeOf((*MockStore)(nil).DeleteArticleTag), ctx, arg)
}

// DeleteCategory mocks base method.
func (m *MockStore) DeleteCategory(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockStoreMockRecorder) DeleteCategory(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockStore)(nil).DeleteCategory), ctx, id)
}

// DeleteCoin mocks base method.
func (m *MockStore) DeleteCoin(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCoin", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCoin indicates an expected call of DeleteCoin.
func (mr *MockStoreMockRecorder) DeleteCoin(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCoin", reflect.TypeOf((*MockStore)(nil).DeleteCoin), ctx, id)
}

// DeleteComment mocks base method.
func (m *MockStore) DeleteComment(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockStoreMockRecorder) DeleteComment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockStore)(nil).DeleteComment), ctx, id)
}

// DeleteFollowRelationship mocks base method.
func (m *MockStore) DeleteFollowRelationship(ctx context.Context, arg db.DeleteFollowRelationshipParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFollowRelationship", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFollowRelationship indicates an expected call of DeleteFollowRelationship.
func (mr *MockStoreMockRecorder) DeleteFollowRelationship(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFollowRelationship", reflect.TypeOf((*MockStore)(nil).DeleteFollowRelationship), ctx, arg)
}

// DeleteTag mocks base method.
func (m *MockStore) DeleteTag(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTag", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTag indicates an expected call of DeleteTag.
func (mr *MockStoreMockRecorder) DeleteTag(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTag", reflect.TypeOf((*MockStore)(nil).DeleteTag), ctx, id)
}

// DeleteUser mocks base method.
func (m *MockStore) DeleteUser(ctx context.Context, uid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStoreMockRecorder) DeleteUser(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStore)(nil).DeleteUser), ctx, uid)
}

// GetArticle mocks base method.
func (m *MockStore) GetArticle(ctx context.Context, id int64) (db.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticle", ctx, id)
	ret0, _ := ret[0].(db.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticle indicates an expected call of GetArticle.
func (mr *MockStoreMockRecorder) GetArticle(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticle", reflect.TypeOf((*MockStore)(nil).GetArticle), ctx, id)
}

// GetArticleCategoryByID mocks base method.
func (m *MockStore) GetArticleCategoryByID(ctx context.Context, id int64) (db.ArticleCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleCategoryByID", ctx, id)
	ret0, _ := ret[0].(db.ArticleCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleCategoryByID indicates an expected call of GetArticleCategoryByID.
func (mr *MockStoreMockRecorder) GetArticleCategoryByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleCategoryByID", reflect.TypeOf((*MockStore)(nil).GetArticleCategoryByID), ctx, id)
}

// GetArticleLike mocks base method.
func (m *MockStore) GetArticleLike(ctx context.Context, arg db.GetArticleLikeParams) (db.ArticleLike, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleLike", ctx, arg)
	ret0, _ := ret[0].(db.ArticleLike)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleLike indicates an expected call of GetArticleLike.
func (mr *MockStoreMockRecorder) GetArticleLike(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleLike", reflect.TypeOf((*MockStore)(nil).GetArticleLike), ctx, arg)
}

// GetArticleLikeByID mocks base method.
func (m *MockStore) GetArticleLikeByID(ctx context.Context, id int64) (db.ArticleLike, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleLikeByID", ctx, id)
	ret0, _ := ret[0].(db.ArticleLike)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleLikeByID indicates an expected call of GetArticleLikeByID.
func (mr *MockStoreMockRecorder) GetArticleLikeByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleLikeByID", reflect.TypeOf((*MockStore)(nil).GetArticleLikeByID), ctx, id)
}

// GetArticleTagByID mocks base method.
func (m *MockStore) GetArticleTagByID(ctx context.Context, id int64) (db.ArticleTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleTagByID", ctx, id)
	ret0, _ := ret[0].(db.ArticleTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleTagByID indicates an expected call of GetArticleTagByID.
func (mr *MockStoreMockRecorder) GetArticleTagByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleTagByID", reflect.TypeOf((*MockStore)(nil).GetArticleTagByID), ctx, id)
}

// GetCategoryByID mocks base method.
func (m *MockStore) GetCategoryByID(ctx context.Context, id int64) (db.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryByID", ctx, id)
	ret0, _ := ret[0].(db.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryByID indicates an expected call of GetCategoryByID.
func (mr *MockStoreMockRecorder) GetCategoryByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryByID", reflect.TypeOf((*MockStore)(nil).GetCategoryByID), ctx, id)
}

// GetCoin mocks base method.
func (m *MockStore) GetCoin(ctx context.Context, id int64) (db.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoin", ctx, id)
	ret0, _ := ret[0].(db.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoin indicates an expected call of GetCoin.
func (mr *MockStoreMockRecorder) GetCoin(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoin", reflect.TypeOf((*MockStore)(nil).GetCoin), ctx, id)
}

// GetCoinEntry mocks base method.
func (m *MockStore) GetCoinEntry(ctx context.Context, id int64) (db.CoinEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoinEntry", ctx, id)
	ret0, _ := ret[0].(db.CoinEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoinEntry indicates an expected call of GetCoinEntry.
func (mr *MockStoreMockRecorder) GetCoinEntry(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoinEntry", reflect.TypeOf((*MockStore)(nil).GetCoinEntry), ctx, id)
}

// GetCoinEntryCount mocks base method.
func (m *MockStore) GetCoinEntryCount(ctx context.Context, coinID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoinEntryCount", ctx, coinID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoinEntryCount indicates an expected call of GetCoinEntryCount.
func (mr *MockStoreMockRecorder) GetCoinEntryCount(ctx, coinID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoinEntryCount", reflect.TypeOf((*MockStore)(nil).GetCoinEntryCount), ctx, coinID)
}

// GetCoinTransfer mocks base method.
func (m *MockStore) GetCoinTransfer(ctx context.Context, id int64) (db.CoinTransfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoinTransfer", ctx, id)
	ret0, _ := ret[0].(db.CoinTransfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoinTransfer indicates an expected call of GetCoinTransfer.
func (mr *MockStoreMockRecorder) GetCoinTransfer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoinTransfer", reflect.TypeOf((*MockStore)(nil).GetCoinTransfer), ctx, id)
}

// GetCoinTransferCount mocks base method.
func (m *MockStore) GetCoinTransferCount(ctx context.Context, fromCoinID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoinTransferCount", ctx, fromCoinID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoinTransferCount indicates an expected call of GetCoinTransferCount.
func (mr *MockStoreMockRecorder) GetCoinTransferCount(ctx, fromCoinID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoinTransferCount", reflect.TypeOf((*MockStore)(nil).GetCoinTransferCount), ctx, fromCoinID)
}

// GetCoinTransferReceived mocks base method.
func (m *MockStore) GetCoinTransferReceived(ctx context.Context, arg db.GetCoinTransferReceivedParams) ([]db.CoinTransfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoinTransferReceived", ctx, arg)
	ret0, _ := ret[0].([]db.CoinTransfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoinTransferReceived indicates an expected call of GetCoinTransferReceived.
func (mr *MockStoreMockRecorder) GetCoinTransferReceived(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoinTransferReceived", reflect.TypeOf((*MockStore)(nil).GetCoinTransferReceived), ctx, arg)
}

// GetComment mocks base method.
func (m *MockStore) GetComment(ctx context.Context, id int64) (db.ArticleComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComment", ctx, id)
	ret0, _ := ret[0].(db.ArticleComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComment indicates an expected call of GetComment.
func (mr *MockStoreMockRecorder) GetComment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComment", reflect.TypeOf((*MockStore)(nil).GetComment), ctx, id)
}

// GetFollowRelationship mocks base method.
func (m *MockStore) GetFollowRelationship(ctx context.Context, arg db.GetFollowRelationshipParams) (db.FollowRelationship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowRelationship", ctx, arg)
	ret0, _ := ret[0].(db.FollowRelationship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowRelationship indicates an expected call of GetFollowRelationship.
func (mr *MockStoreMockRecorder) GetFollowRelationship(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowRelationship", reflect.TypeOf((*MockStore)(nil).GetFollowRelationship), ctx, arg)
}

// GetFollowRelationshipByID mocks base method.
func (m *MockStore) GetFollowRelationshipByID(ctx context.Context, id int64) (db.FollowRelationship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowRelationshipByID", ctx, id)
	ret0, _ := ret[0].(db.FollowRelationship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowRelationshipByID indicates an expected call of GetFollowRelationshipByID.
func (mr *MockStoreMockRecorder) GetFollowRelationshipByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowRelationshipByID", reflect.TypeOf((*MockStore)(nil).GetFollowRelationshipByID), ctx, id)
}

// GetTagByID mocks base method.
func (m *MockStore) GetTagByID(ctx context.Context, id int64) (db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagByID", ctx, id)
	ret0, _ := ret[0].(db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagByID indicates an expected call of GetTagByID.
func (mr *MockStoreMockRecorder) GetTagByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagByID", reflect.TypeOf((*MockStore)(nil).GetTagByID), ctx, id)
}

// GetTagByName mocks base method.
func (m *MockStore) GetTagByName(ctx context.Context, name string) (db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagByName", ctx, name)
	ret0, _ := ret[0].(db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagByName indicates an expected call of GetTagByName.
func (mr *MockStoreMockRecorder) GetTagByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagByName", reflect.TypeOf((*MockStore)(nil).GetTagByName), ctx, name)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(ctx context.Context, uid int64) (db.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, uid)
	ret0, _ := ret[0].(db.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), ctx, uid)
}

// IncrementArticleCommentCount mocks base method.
func (m *MockStore) IncrementArticleCommentCount(ctx context.Context, id int64) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementArticleCommentCount", ctx, id)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementArticleCommentCount indicates an expected call of IncrementArticleCommentCount.
func (mr *MockStoreMockRecorder) IncrementArticleCommentCount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementArticleCommentCount", reflect.TypeOf((*MockStore)(nil).IncrementArticleCommentCount), ctx, id)
}

// IncrementArticleLikeCount mocks base method.
func (m *MockStore) IncrementArticleLikeCount(ctx context.Context, id int64) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementArticleLikeCount", ctx, id)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementArticleLikeCount indicates an expected call of IncrementArticleLikeCount.
func (mr *MockStoreMockRecorder) IncrementArticleLikeCount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementArticleLikeCount", reflect.TypeOf((*MockStore)(nil).IncrementArticleLikeCount), ctx, id)
}

// IncrementArticleViewCount mocks base method.
func (m *MockStore) IncrementArticleViewCount(ctx context.Context, id int64) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementArticleViewCount", ctx, id)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementArticleViewCount indicates an expected call of IncrementArticleViewCount.
func (mr *MockStoreMockRecorder) IncrementArticleViewCount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementArticleViewCount", reflect.TypeOf((*MockStore)(nil).IncrementArticleViewCount), ctx, id)
}

// ListArticleByCategory mocks base method.
func (m *MockStore) ListArticleByCategory(ctx context.Context, arg db.ListArticleByCategoryParams) ([]db.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArticleByCategory", ctx, arg)
	ret0, _ := ret[0].([]db.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArticleByCategory indicates an expected call of ListArticleByCategory.
func (mr *MockStoreMockRecorder) ListArticleByCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticleByCategory", reflect.TypeOf((*MockStore)(nil).ListArticleByCategory), ctx, arg)
}

// ListArticleByTag mocks base method.
func (m *MockStore) ListArticleByTag(ctx context.Context, arg db.ListArticleByTagParams) ([]db.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArticleByTag", ctx, arg)
	ret0, _ := ret[0].([]db.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArticleByTag indicates an expected call of ListArticleByTag.
func (mr *MockStoreMockRecorder) ListArticleByTag(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticleByTag", reflect.TypeOf((*MockStore)(nil).ListArticleByTag), ctx, arg)
}

// ListArticleLikesByArticle mocks base method.
func (m *MockStore) ListArticleLikesByArticle(ctx context.Context, arg db.ListArticleLikesByArticleParams) ([]db.ArticleLike, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArticleLikesByArticle", ctx, arg)
	ret0, _ := ret[0].([]db.ArticleLike)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArticleLikesByArticle indicates an expected call of ListArticleLikesByArticle.
func (mr *MockStoreMockRecorder) ListArticleLikesByArticle(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticleLikesByArticle", reflect.TypeOf((*MockStore)(nil).ListArticleLikesByArticle), ctx, arg)
}

// ListArticles mocks base method.
func (m *MockStore) ListArticles(ctx context.Context, arg db.ListArticlesParams) ([]db.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArticles", ctx, arg)
	ret0, _ := ret[0].([]db.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArticles indicates an expected call of ListArticles.
func (mr *MockStoreMockRecorder) ListArticles(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticles", reflect.TypeOf((*MockStore)(nil).ListArticles), ctx, arg)
}

// ListArticlesByCategoryID mocks base method.
func (m *MockStore) ListArticlesByCategoryID(ctx context.Context, arg db.ListArticlesByCategoryIDParams) ([]db.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArticlesByCategoryID", ctx, arg)
	ret0, _ := ret[0].([]db.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArticlesByCategoryID indicates an expected call of ListArticlesByCategoryID.
func (mr *MockStoreMockRecorder) ListArticlesByCategoryID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticlesByCategoryID", reflect.TypeOf((*MockStore)(nil).ListArticlesByCategoryID), ctx, arg)
}

// ListArticlesByCommentCount mocks base method.
func (m *MockStore) ListArticlesByCommentCount(ctx context.Context, arg db.ListArticlesByCommentCountParams) ([]db.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArticlesByCommentCount", ctx, arg)
	ret0, _ := ret[0].([]db.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArticlesByCommentCount indicates an expected call of ListArticlesByCommentCount.
func (mr *MockStoreMockRecorder) ListArticlesByCommentCount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticlesByCommentCount", reflect.TypeOf((*MockStore)(nil).ListArticlesByCommentCount), ctx, arg)
}

// ListArticlesByLikeCount mocks base method.
func (m *MockStore) ListArticlesByLikeCount(ctx context.Context, arg db.ListArticlesByLikeCountParams) ([]db.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArticlesByLikeCount", ctx, arg)
	ret0, _ := ret[0].([]db.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArticlesByLikeCount indicates an expected call of ListArticlesByLikeCount.
func (mr *MockStoreMockRecorder) ListArticlesByLikeCount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticlesByLikeCount", reflect.TypeOf((*MockStore)(nil).ListArticlesByLikeCount), ctx, arg)
}

// ListArticlesByTagID mocks base method.
func (m *MockStore) ListArticlesByTagID(ctx context.Context, arg db.ListArticlesByTagIDParams) ([]db.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArticlesByTagID", ctx, arg)
	ret0, _ := ret[0].([]db.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArticlesByTagID indicates an expected call of ListArticlesByTagID.
func (mr *MockStoreMockRecorder) ListArticlesByTagID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticlesByTagID", reflect.TypeOf((*MockStore)(nil).ListArticlesByTagID), ctx, arg)
}

// ListArticlesByViewCount mocks base method.
func (m *MockStore) ListArticlesByViewCount(ctx context.Context, arg db.ListArticlesByViewCountParams) ([]db.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArticlesByViewCount", ctx, arg)
	ret0, _ := ret[0].([]db.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArticlesByViewCount indicates an expected call of ListArticlesByViewCount.
func (mr *MockStoreMockRecorder) ListArticlesByViewCount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticlesByViewCount", reflect.TypeOf((*MockStore)(nil).ListArticlesByViewCount), ctx, arg)
}

// ListCategories mocks base method.
func (m *MockStore) ListCategories(ctx context.Context) ([]db.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", ctx)
	ret0, _ := ret[0].([]db.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockStoreMockRecorder) ListCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockStore)(nil).ListCategories), ctx)
}

// ListCategoriesByArticle mocks base method.
func (m *MockStore) ListCategoriesByArticle(ctx context.Context, arg db.ListCategoriesByArticleParams) ([]db.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategoriesByArticle", ctx, arg)
	ret0, _ := ret[0].([]db.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategoriesByArticle indicates an expected call of ListCategoriesByArticle.
func (mr *MockStoreMockRecorder) ListCategoriesByArticle(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategoriesByArticle", reflect.TypeOf((*MockStore)(nil).ListCategoriesByArticle), ctx, arg)
}

// ListCoinTransfer mocks base method.
func (m *MockStore) ListCoinTransfer(ctx context.Context, arg db.ListCoinTransferParams) ([]db.CoinTransfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCoinTransfer", ctx, arg)
	ret0, _ := ret[0].([]db.CoinTransfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCoinTransfer indicates an expected call of ListCoinTransfer.
func (mr *MockStoreMockRecorder) ListCoinTransfer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCoinTransfer", reflect.TypeOf((*MockStore)(nil).ListCoinTransfer), ctx, arg)
}

// ListCoins mocks base method.
func (m *MockStore) ListCoins(ctx context.Context, arg db.ListCoinsParams) ([]db.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCoins", ctx, arg)
	ret0, _ := ret[0].([]db.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCoins indicates an expected call of ListCoins.
func (mr *MockStoreMockRecorder) ListCoins(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCoins", reflect.TypeOf((*MockStore)(nil).ListCoins), ctx, arg)
}

// ListCoinsForUser mocks base method.
func (m *MockStore) ListCoinsForUser(ctx context.Context, arg db.ListCoinsForUserParams) ([]db.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCoinsForUser", ctx, arg)
	ret0, _ := ret[0].([]db.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCoinsForUser indicates an expected call of ListCoinsForUser.
func (mr *MockStoreMockRecorder) ListCoinsForUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCoinsForUser", reflect.TypeOf((*MockStore)(nil).ListCoinsForUser), ctx, arg)
}

// ListComments mocks base method.
func (m *MockStore) ListComments(ctx context.Context, arg db.ListCommentsParams) ([]db.ArticleComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComments", ctx, arg)
	ret0, _ := ret[0].([]db.ArticleComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListComments indicates an expected call of ListComments.
func (mr *MockStoreMockRecorder) ListComments(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComments", reflect.TypeOf((*MockStore)(nil).ListComments), ctx, arg)
}

// ListEntries mocks base method.
func (m *MockStore) ListEntries(ctx context.Context, arg db.ListEntriesParams) ([]db.CoinEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEntries", ctx, arg)
	ret0, _ := ret[0].([]db.CoinEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEntries indicates an expected call of ListEntries.
func (mr *MockStoreMockRecorder) ListEntries(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEntries", reflect.TypeOf((*MockStore)(nil).ListEntries), ctx, arg)
}

// ListFollowers mocks base method.
func (m *MockStore) ListFollowers(ctx context.Context, arg db.ListFollowersParams) ([]db.FollowRelationship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowers", ctx, arg)
	ret0, _ := ret[0].([]db.FollowRelationship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFollowers indicates an expected call of ListFollowers.
func (mr *MockStoreMockRecorder) ListFollowers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowers", reflect.TypeOf((*MockStore)(nil).ListFollowers), ctx, arg)
}

// ListFollowing mocks base method.
func (m *MockStore) ListFollowing(ctx context.Context, arg db.ListFollowingParams) ([]db.FollowRelationship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowing", ctx, arg)
	ret0, _ := ret[0].([]db.FollowRelationship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFollowing indicates an expected call of ListFollowing.
func (mr *MockStoreMockRecorder) ListFollowing(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowing", reflect.TypeOf((*MockStore)(nil).ListFollowing), ctx, arg)
}

// ListTags mocks base method.
func (m *MockStore) ListTags(ctx context.Context, arg db.ListTagsParams) ([]db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTags", ctx, arg)
	ret0, _ := ret[0].([]db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *MockStoreMockRecorder) ListTags(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MockStore)(nil).ListTags), ctx, arg)
}

// ListTagsByArticle mocks base method.
func (m *MockStore) ListTagsByArticle(ctx context.Context, arg db.ListTagsByArticleParams) ([]db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTagsByArticle", ctx, arg)
	ret0, _ := ret[0].([]db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTagsByArticle indicates an expected call of ListTagsByArticle.
func (mr *MockStoreMockRecorder) ListTagsByArticle(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTagsByArticle", reflect.TypeOf((*MockStore)(nil).ListTagsByArticle), ctx, arg)
}

// ListTransfer mocks base method.
func (m *MockStore) ListTransfer(ctx context.Context, arg db.ListTransferParams) ([]db.CoinTransfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransfer", ctx, arg)
	ret0, _ := ret[0].([]db.CoinTransfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransfer indicates an expected call of ListTransfer.
func (mr *MockStoreMockRecorder) ListTransfer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransfer", reflect.TypeOf((*MockStore)(nil).ListTransfer), ctx, arg)
}

// ListUsers mocks base method.
func (m *MockStore) ListUsers(ctx context.Context, arg db.ListUsersParams) ([]db.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, arg)
	ret0, _ := ret[0].([]db.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockStoreMockRecorder) ListUsers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockStore)(nil).ListUsers), ctx, arg)
}

// UpdateArticle mocks base method.
func (m *MockStore) UpdateArticle(ctx context.Context, arg db.UpdateArticleParams) (db.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateArticle", ctx, arg)
	ret0, _ := ret[0].(db.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateArticle indicates an expected call of UpdateArticle.
func (mr *MockStoreMockRecorder) UpdateArticle(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArticle", reflect.TypeOf((*MockStore)(nil).UpdateArticle), ctx, arg)
}

// UpdateCategory mocks base method.
func (m *MockStore) UpdateCategory(ctx context.Context, arg db.UpdateCategoryParams) (db.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, arg)
	ret0, _ := ret[0].(db.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockStoreMockRecorder) UpdateCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockStore)(nil).UpdateCategory), ctx, arg)
}

// UpdateCoin mocks base method.
func (m *MockStore) UpdateCoin(ctx context.Context, arg db.UpdateCoinParams) (db.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCoin", ctx, arg)
	ret0, _ := ret[0].(db.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCoin indicates an expected call of UpdateCoin.
func (mr *MockStoreMockRecorder) UpdateCoin(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCoin", reflect.TypeOf((*MockStore)(nil).UpdateCoin), ctx, arg)
}

// UpdateTag mocks base method.
func (m *MockStore) UpdateTag(ctx context.Context, arg db.UpdateTagParams) (db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTag", ctx, arg)
	ret0, _ := ret[0].(db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTag indicates an expected call of UpdateTag.
func (mr *MockStoreMockRecorder) UpdateTag(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTag", reflect.TypeOf((*MockStore)(nil).UpdateTag), ctx, arg)
}

// UpdateUser mocks base method.
func (m *MockStore) UpdateUser(ctx context.Context, arg db.UpdateUserParams) (db.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, arg)
	ret0, _ := ret[0].(db.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStoreMockRecorder) UpdateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStore)(nil).UpdateUser), ctx, arg)
}
